export const INPUT_TEXT = 'INPUT_TEXT';
export const INPUT_CREATE = 'INPUT_CREATE';
export const INPUT_UPDATE = 'INPUT_UPDATE';

export const INPUT_DELETE = 'INPUT_DELETE';
export const INPUT_DELETE_ALL = 'INPUT_DELETE_ALL';
export const INPUT_COMPLETED_ALL = 'INPUT_COMPLETED_ALL';

export const INPUT_LOAD = 'INPUT_LOAD';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';

export const ERROR_DISPLAY_ON = 'ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF = 'ERROR_DISPLAY_OFF';